### ISSUE TITLE
bungeecord slp support

### ISSUE THREAD

**Issue by Wqrld** [jonthesquirrel/ServerListPlus-PlaceholderAPI#4]
Can you add support for placeholderapi on bungee slp too? like get the variables from a plugin on one of the subservers

I want to have slp show all online players on the network so i can't enable ping passthrough

**Comment by comfysquirrel** [comment]
I'll see what I can do!

**Comment by comfysquirrel** [comment]
I'll add the `@server` syntax too, similar to SLP's [`random_players`](https://github.com/Minecrell/ServerListPlus/wiki/Placeholders#random-player-list)

**Comment by comfysquirrel** [comment]
I'm sorry but I won't be adding bungee support as it adds a lot of complication and I won't be needing bungee for my setup. Feel free to fork it and try to add support yourself though
